# Generated by Django 5.0.4 on 2024-05-14 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photo',
            field=models.ImageField(default='no_image.jpg', upload_to='product_photos/'),
        ),
    ]
